# Generated by Django 5.2.6 on 2025-09-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', editable=False, max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('CC', 'Cedula'), ('PP', 'Pasaporte')], max_length=2)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.CharField(max_length=5)),
                ('security_code', models.CharField(max_length=4)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
