# Generated by Django 5.2.6 on 2025-09-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='document_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
