# Generated by Django 5.2.6 on 2025-09-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
