# Generated by Django 5.2.6 on 2025-09-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
