"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.
...
"""

from pathlib import Path
import os
from decouple import config
import dj_database_url # Para configurar PostgreSQL con una URL


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# 🌟 CRUCIAL: Establecido en True por defecto para ejecución local
DEBUG = config('DEBUG', default=True, cast=bool) 

# Hosts permitidos
ALLOWED_HOSTS = ['*']


# --------------------------------------------------------------------------
# 🌟 CONFIGURACIÓN CORS PARA AMBIENTE LOCAL
# --------------------------------------------------------------------------
# Esto permite que React (localhost:5173) se conecte a Django (localhost:8000)
CORS_ALLOW_ALL_ORIGINS = True 
CORS_ALLOW_CREDENTIALS = True 

# Orígenes de confianza para cookies CSRF
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173', 
    'http://127.0.0.1:5173',
]
# --------------------------------------------------------------------------


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', # Para la api Rest 
    'corsheaders', # Para permitir la comunicación con React
    'transactions', # Nuestra aplicación de transacciones'
    'rest_framework_simplejwt', # Autenticación
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # 1. Debe ir antes de SecurityMiddleware
    'django.middleware.security.SecurityMiddleware', # 2
    'django.contrib.sessions.middleware.SessionMiddleware', # 3 
    'django.middleware.common.CommonMiddleware', # 4
    'django.middleware.csrf.CsrfViewMiddleware', # 5
    'django.contrib.auth.middleware.AuthenticationMiddleware', #6 
    'django.contrib.messages.middleware.MessageMiddleware', # 7
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # 8
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# Base de datos en SQLite por defecto para ejecución local
DATABASES = {
    'default': config(
        'DATABASE_URL',
        default='sqlite:///db.sqlite3',
        cast=dj_database_url.parse
    )
}

# Password validation... (sin cambios)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization... (sin cambios)
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
# Eliminamos la configuración de Whitenoise para simplificar la ejecución local

# Default primary key field type... (sin cambios)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuración de Django REST Framework... (sin cambios)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# Configuración de Cookies y Headers... (sin cambios)
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_SAMESITE = None 
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken', 
    'x-requested-with',
]